import { Link } from "@tanstack/react-router";
import { Activity, CheckCircle2, CircleAlert, Clock3, Play, Pause, Radio, ShieldCheck, Siren, Wrench } from "lucide-react";
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis } from "recharts";
import { motion } from "motion/react";
import { useApp } from "@/context/app-context";
import { issueTypes } from "@/data/mock-data";
import { LazyMap } from "@/components/map/lazy-map";
import { Panel, PanelHeader, PriorityBadge, StatusBadge, timeAgo } from "@/components/common/ui";
import { Button } from "@/components/ui/button";
const statusColors = ["var(--success)", "var(--warning)", "var(--info)", "var(--critical)"];
export function SimulationControls() { const { isRunning, setRunning, speed, setSpeed, generateIssue } = useApp(); return <div className="flex flex-wrap items-center gap-2"><div className={`hidden items-center gap-2 rounded-md px-2.5 py-2 text-xs font-semibold sm:flex ${isRunning ? "bg-success-soft text-success" : "bg-muted text-muted-foreground"}`}><span className={isRunning ? "status-dot" : "h-2 w-2 rounded-full bg-muted-foreground"}/>{isRunning ? "Running" : "Paused"}</div><select aria-label="Simulation speed" className="control h-9 w-24" value={speed} onChange={(e) => setSpeed(e.target.value as typeof speed)}><option>Slow</option><option>Normal</option><option>Fast</option></select><Button size="sm" variant={isRunning ? "outline" : "default"} onClick={() => setRunning(!isRunning)}>{isRunning ? <Pause/> : <Play/>}{isRunning ? "Pause" : "Live simulation"}</Button><Button size="sm" variant="secondary" onClick={generateIssue}>Generate now</Button></div>; }
export function DashboardPage() { const { issues, activities } = useApp(); const critical = issues.filter(i=>i.priority === "Critical" && i.status !== "Resolved").length; const progress = issues.filter(i=>i.status === "In Progress").length; const resolved = issues.filter(i=>i.status === "Resolved").length;
  const stats = [{label:"Total Issues",value:issues.length,detail:"+12.4% from last week",icon:CircleAlert,tone:"info"},{label:"Critical Issues",value:critical,detail:"Requires attention",icon:Siren,tone:"critical"},{label:"In Progress",value:progress,detail:"Active response",icon:Clock3,tone:"warning"},{label:"Resolved",value:resolved,detail:"+8.7% this period",icon:CheckCircle2,tone:"success"}];
  const typeData = issueTypes.map(type=>({name:type.replace("Streetlight Failure","Streetlights").replace("Traffic Anomaly","Traffic"),value:issues.filter(i=>i.type===type).length})); const statusData = ["Resolved","In Progress","Assigned","Pending"].map(name=>({name,value:issues.filter(i=>i.status===name).length}));
  return <motion.div className="space-y-4" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}}><div className="flex flex-col justify-end gap-3 sm:flex-row"><SimulationControls/></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({label,value,detail,icon:Icon,tone},i)=><motion.div key={label} className="stat-card" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:i*.06}}><div className={`stat-icon tone-${tone}`}><Icon/></div><div><p className="text-xs font-semibold text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-black">{value.toLocaleString()}</p><p className={`mt-1 text-[10px] tone-text-${tone}`}>{detail}</p></div></motion.div>)}</div>
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1.8fr)_minmax(300px,.7fr)]"><Panel className="p-2"><div className="px-2 pt-2"><PanelHeader title="Live Urban Monitoring" subtitle={`${issues.filter(i=>i.status!=="Resolved").length} active detections across Mumbai`} action={<Link className="text-xs font-semibold text-primary" to="/map">Open live map</Link>}/></div><LazyMap issues={issues} className="h-[430px]" /></Panel><div className="grid gap-4"><Panel><PanelHeader title="Recent Alerts" action={<Link className="text-xs font-semibold text-primary" to="/alerts">View all</Link>}/><div className="space-y-2">{issues.slice(0,4).map(i=><Link key={i.id} to="/issues/$id" params={{id:i.id}} className="alert-row"><div className="min-w-0"><p className="truncate text-xs font-bold">{i.type} detected</p><p className="truncate text-[10px] text-muted-foreground">{i.location} · {i.confidence}%</p></div><PriorityBadge value={i.priority}/></Link>)}</div></Panel><Panel><PanelHeader title="Recent Activity"/><div className="activity-list">{activities.slice(0,4).map(a=><div key={a.id} className="activity-item"><span className={`activity-dot ${a.tone}`}/><div className="min-w-0"><p className="truncate text-xs font-semibold">{a.title}</p><p className="truncate text-[10px] text-muted-foreground">{a.detail}</p></div><span className="ml-auto shrink-0 text-[9px] text-muted-foreground">{timeAgo(a.timestamp)}</span></div>)}</div></Panel></div></div>
    <div className="grid gap-4 lg:grid-cols-[1.2fr_.9fr_.7fr]"><Panel><PanelHeader title="Issues by Type"/><div className="h-44"><ResponsiveContainer><BarChart data={typeData}><XAxis dataKey="name" tick={{fontSize:9}} interval={0}/><Tooltip/><Bar dataKey="value" fill="var(--primary)" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></Panel><Panel><PanelHeader title="Resolution Status"/><div className="relative h-44"><ResponsiveContainer><PieChart><Pie data={statusData} dataKey="value" innerRadius={48} outerRadius={68} paddingAngle={2}>{statusData.map((_,i)=><Cell key={i} fill={statusColors[i]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 grid place-items-center"><div className="text-center"><p className="text-xl font-black">{issues.length}</p><p className="text-[9px] text-muted-foreground">Total issues</p></div></div></div></Panel><Panel><PanelHeader title="System Status"/><div className="space-y-3">{[["Detection Engine","Online"],["Location Services","Online"],["Monitoring","Active"],["Data Processing","Online"]].map(([a,b])=><div className="flex items-center gap-2" key={a}><span className="status-dot"/><span className="text-xs">{a}</span><span className="ml-auto text-[10px] font-semibold text-success">{b}</span></div>)}</div><div className="mt-5 flex items-center gap-2 rounded-md bg-success-soft p-2 text-[10px] text-success"><ShieldCheck className="h-4 w-4"/>Last update just now</div></Panel></div>
  </motion.div>;
}
