import { useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Filter, SlidersHorizontal } from "lucide-react";
import { motion } from "motion/react";
import { useApp } from "@/context/app-context";
import { issueTypes, priorities, statuses, trendData } from "@/data/mock-data";
import { LazyMap } from "@/components/map/lazy-map";
import { Panel, PanelHeader } from "@/components/common/ui";
import { Button } from "@/components/ui/button";
import type { AppSettings, IssueType } from "@/lib/urbaneye-types";
const chartColors=["var(--critical)","var(--high)","var(--medium)","var(--success)"];
export function LiveMapPage(){const {issues}=useApp();const [mobileFilters,setMobileFilters]=useState(false);const [selectedTypes,setSelectedTypes]=useState<IssueType[]>(issueTypes);const [priority,setPriority]=useState("All");const [status,setStatus]=useState("All");const filtered=issues.filter(i=>selectedTypes.includes(i.type)&&(priority==="All"||i.priority===priority)&&(status==="All"||i.status===status));const filters=<div className="space-y-5"><FilterBlock title="Issue type">{issueTypes.map(t=><label key={t} className="check-row"><input type="checkbox" checked={selectedTypes.includes(t)} onChange={()=>setSelectedTypes(v=>v.includes(t)?v.filter(x=>x!==t):[...v,t])}/><span>{t}</span></label>)}</FilterBlock><FilterBlock title="Priority"><select className="control" value={priority} onChange={e=>setPriority(e.target.value)}><option>All</option>{priorities.map(v=><option key={v}>{v}</option>)}</select></FilterBlock><FilterBlock title="Status"><select className="control" value={status} onChange={e=>setStatus(e.target.value)}><option>All</option>{statuses.map(v=><option key={v}>{v}</option>)}</select></FilterBlock><FilterBlock title="Date range"><select className="control"><option>Today</option><option>Last 7 Days</option><option>Last 30 Days</option></select></FilterBlock><Button variant="outline" className="w-full" onClick={()=>{setSelectedTypes(issueTypes);setPriority("All");setStatus("All")}}>Reset filters</Button></div>;return <motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}}><div className="mb-3 flex items-center justify-between lg:hidden"><p className="text-xs text-muted-foreground">{filtered.length} visible detections</p><Button size="sm" variant="outline" onClick={()=>setMobileFilters(!mobileFilters)}><SlidersHorizontal/>Filters</Button></div>{mobileFilters&&<Panel className="mb-3 lg:hidden">{filters}</Panel>}<div className="grid gap-4 lg:grid-cols-[240px_minmax(0,1fr)]"><Panel className="hidden lg:block"><PanelHeader title="Map Filters"/>{filters}</Panel><Panel className="p-2"><LazyMap issues={filtered} className="h-[calc(100vh-7.5rem)] min-h-[520px]"/></Panel></div></motion.div>}
function FilterBlock({title,children}:{title:string;children:React.ReactNode}){return <fieldset><legend className="mb-2 text-xs font-bold">{title}</legend><div className="space-y-2">{children}</div></fieldset>}
export function AnalyticsPage(){const {issues}=useApp();const typeData=issueTypes.map(name=>({name:name.replace("Streetlight Failure","Streetlight").replace("Traffic Anomaly","Traffic"),value:issues.filter(i=>i.type===name).length}));const priorityData=priorities.map(name=>({name,value:issues.filter(i=>i.priority===name).length}));const areaData=Array.from(new Set(issues.map(i=>i.area))).slice(0,6).map(name=>({name,value:issues.filter(i=>i.area===name).length}));const open=issues.filter(i=>i.status!=="Resolved").length;return <motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="space-y-4"><div className="grid gap-4 xl:grid-cols-2"><ChartPanel title="Issues by Category"><BarChart data={typeData}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:9}}/><YAxis tick={{fontSize:9}}/><Tooltip/><Bar dataKey="value" fill="var(--primary)" radius={[4,4,0,0]}/></BarChart></ChartPanel><ChartPanel title="Issues Over Time"><LineChart data={trendData}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="day" tick={{fontSize:9}} interval={5}/><YAxis tick={{fontSize:9}}/><Tooltip/><Line type="monotone" dataKey="issues" stroke="var(--primary)" strokeWidth={2} dot={false}/></LineChart></ChartPanel><ChartPanel title="Priority Distribution"><PieChart><Pie data={priorityData} dataKey="value" nameKey="name" innerRadius={55} outerRadius={82}>{priorityData.map((_,i)=><Cell key={i} fill={chartColors[i]}/>)}</Pie><Tooltip/></PieChart></ChartPanel><ChartPanel title="Area-wise Issues"><BarChart data={areaData} layout="vertical"><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" tick={{fontSize:9}}/><YAxis type="category" dataKey="name" width={75} tick={{fontSize:9}}/><Tooltip/><Bar dataKey="value" fill="var(--info)" radius={[0,4,4,0]}/></BarChart></ChartPanel></div><Panel><PanelHeader title="Resolution Performance"/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Average Resolution Time","4h 18m"],["Critical Issues Resolved","86%"],["Open Issues",String(open)],["Resolved Today",String(issues.filter(i=>i.status==="Resolved").length)]].map(([label,value])=><div className="metric-block" key={label}><p className="text-2xl font-black">{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></div>)}</div></Panel></motion.div>}
function ChartPanel({title,children}:{title:string;children:React.ReactElement}){return <Panel><PanelHeader title={title}/><div className="h-64"><ResponsiveContainer>{children}</ResponsiveContainer></div></Panel>}
export function SettingsPage(){const {settings,setSettings,isRunning,setRunning,speed,setSpeed,selectedTypes,setSelectedTypes}=useApp();const toggle=(key:keyof AppSettings)=>setSettings({...settings,[key]:!settings[key]});const interfaceSettings: Array<[keyof AppSettings,string]>=[["compact","Compact mode"],["animations","Interface animations"],["autoRefresh","Auto refresh"]];const notificationSettings: Array<[keyof AppSettings,string]>=[["desktopNotifications","Desktop notifications"],["criticalAlerts","Critical alerts"],["newIssueAlerts","New issue alerts"]];return <motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="grid gap-4 xl:grid-cols-3"><SettingsSection title="Interface" subtitle="Control the operations workspace appearance.">{interfaceSettings.map(([key,label])=><ToggleRow key={key} label={label} value={Boolean(settings[key])} onChange={()=>toggle(key)}/>)}</SettingsSection><SettingsSection title="Simulation" subtitle="Configure live detection events."><ToggleRow label="Simulation enabled" value={isRunning} onChange={()=>setRunning(!isRunning)}/><label className="setting-row"><span>Frequency</span><select className="control w-28" value={speed} onChange={e=>setSpeed(e.target.value as typeof speed)}><option>Slow</option><option>Normal</option><option>Fast</option></select></label><div className="pt-3"><p className="mb-2 text-xs font-semibold">Preferred issue types</p>{issueTypes.map(t=><label key={t} className="check-row"><input type="checkbox" checked={selectedTypes.includes(t)} onChange={()=>setSelectedTypes(selectedTypes.includes(t)?selectedTypes.filter(x=>x!==t):[...selectedTypes,t])}/>{t}</label>)}</div></SettingsSection><SettingsSection title="Notifications" subtitle="Choose which events should draw attention.">{notificationSettings.map(([key,label])=><ToggleRow key={key} label={label} value={Boolean(settings[key])} onChange={()=>toggle(key)}/>)}</SettingsSection></motion.div>}
function SettingsSection({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <Panel><PanelHeader title={title} subtitle={subtitle}/><div className="divide-y divide-border">{children}</div></Panel>}
function ToggleRow({label,value,onChange}:{label:string;value:boolean;onChange:()=>void}){return <div className="setting-row"><span>{label}</span><button type="button" role="switch" aria-checked={value} onClick={onChange} className={`toggle ${value?"on":""}`}><span/></button></div>}
